/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DogsImport } from './routes/dogs'
import { Route as CustomersImport } from './routes/customers'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const DogsRoute = DogsImport.update({
  id: '/dogs',
  path: '/dogs',
  getParentRoute: () => rootRoute,
} as any)

const CustomersRoute = CustomersImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersImport
      parentRoute: typeof rootRoute
    }
    '/dogs': {
      id: '/dogs'
      path: '/dogs'
      fullPath: '/dogs'
      preLoaderRoute: typeof DogsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dogs': typeof DogsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dogs': typeof DogsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dogs': typeof DogsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/customers' | '/dogs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/customers' | '/dogs'
  id: '__root__' | '/' | '/customers' | '/dogs'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  DogsRoute: typeof DogsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  DogsRoute: DogsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/customers",
        "/dogs"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/customers": {
      "filePath": "customers.tsx"
    },
    "/dogs": {
      "filePath": "dogs.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
